services:
  koreader:
    image: ghcr.io/zephyros-dev/koreader:latest
    container_name: koreader-emulator
    ports:
      - '3000:3000' # Web interface http://localhost:3000
      - '3001:3001' # HTTPS
    cap_add:
      - CAP_NET_RAW
    shm_size: '1gb'
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./books:/books
      - ./unitlens.koplugin:/config/.config/koreader/plugins/unitlens.koplugin
      - ./volume/config:/config
    restart: unless-stopped
