--[[
dicts/ru.lua - Russian dictionary (length, mass, volume, area).

Format: see docs/spec.md §4. Values are precomputed strings with a comma decimal
mark (docs/units.md). Imperial units carry no symbols in Russian prose; only the
metric side declares digit-gated symbols (км, гм, дам, м, дм, см, мм, мкм, нм,
т, ц, кг, г, мг, мкг, гл, л, дл, мл, га).

Single-word only (the matcher tests one token at a time). Units that share one
word across systems are folded into a single entry with several labelled results,
so the reader picks by context: миля (сухопутная/морская), тонна (метрическая/
длинная/короткая), хандредвейт (брит./амер.), галлон/кварта/пинта (амер./брит.),
унция (вес + жидк. амер./брит., cross-category so header-less).
]]

return {
	lang = "ru",
	name = "Русский",

	strings = {
		system_label = "Система",
		category_label = "Категория",
		systems = { customary = "Имперская", metric = "Метрическая" },
		categories = { length = "Длина", mass = "Масса", volume = "Объём", area = "Площадь" },
	},

	units = {

		-- ── Length ────────────────────────────────────────────────────────
		league = {
			name = "лига",
			system = "customary",
			category = "length",
			forms = {
				"лига",
				"лиги",
				"лиге",
				"лигу",
				"лигой",
				"лигою",
				"лиг",
				"лигам",
				"лигами",
				"лигах",
			},
			results = { { value = "4,828", unit = "км" } },
		},
		mile = {
			name = "миля",
			system = "customary",
			category = "length",
			forms = {
				"миля",
				"мили",
				"миле",
				"милю",
				"милей",
				"милею",
				"миль",
				"милям",
				"милями",
				"милях",
			},
			results = {
				{ value = "1,609", unit = "км", label = "сухопутная" },
				{ value = "1,852", unit = "км", label = "морская" },
			},
		},
		furlong = {
			name = "фурлонг",
			system = "customary",
			category = "length",
			forms = {
				"фурлонг",
				"фурлонга",
				"фурлонгу",
				"фурлонгом",
				"фурлонге",
				"фурлонги",
				"фурлонгов",
				"фурлонгам",
				"фурлонгами",
				"фурлонгах",
			},
			results = { { value = "201,17", unit = "м" } },
		},
		chain = {
			name = "чейн",
			system = "customary",
			category = "length",
			forms = {
				"чейн",
				"чейна",
				"чейну",
				"чейном",
				"чейне",
				"чейны",
				"чейнов",
				"чейнам",
				"чейнами",
				"чейнах",
			},
			results = { { value = "20,117", unit = "м" } },
		},
		yard = {
			name = "ярд",
			system = "customary",
			category = "length",
			forms = {
				"ярд",
				"ярда",
				"ярду",
				"ярдом",
				"ярде",
				"ярды",
				"ярдов",
				"ярдам",
				"ярдами",
				"ярдах",
			},
			results = { { value = "0,9144", unit = "м" } },
		},
		foot = {
			name = "фут",
			system = "customary",
			category = "length",
			forms = {
				"фут",
				"фута",
				"футу",
				"футом",
				"футе",
				"футы",
				"футов",
				"футам",
				"футами",
				"футах",
			},
			results = { { value = "0,3048", unit = "м" } },
		},
		inch = {
			name = "дюйм",
			system = "customary",
			category = "length",
			forms = {
				"дюйм",
				"дюйма",
				"дюйму",
				"дюймом",
				"дюйме",
				"дюймы",
				"дюймов",
				"дюймам",
				"дюймами",
				"дюймах",
			},
			results = { { value = "2,54", unit = "см" } },
		},
		kilometre = {
			name = "километр",
			system = "metric",
			category = "length",
			symbols = { "км" },
			forms = {
				"километр",
				"километра",
				"километру",
				"километром",
				"километре",
				"километры",
				"километров",
				"километрам",
				"километрами",
				"километрах",
			},
			results = { { value = "0,6214", unit = "мили" } },
		},
		hectometre = {
			name = "гектометр",
			system = "metric",
			category = "length",
			symbols = { "гм" },
			forms = {
				"гектометр",
				"гектометра",
				"гектометру",
				"гектометром",
				"гектометре",
				"гектометры",
				"гектометров",
				"гектометрам",
				"гектометрами",
				"гектометрах",
			},
			results = {
				{ value = "100", unit = "м" },
				{ value = "328,08", unit = "фута" },
			},
		},
		decametre = {
			name = "декаметр",
			system = "metric",
			category = "length",
			symbols = { "дам" },
			forms = {
				"декаметр",
				"декаметра",
				"декаметру",
				"декаметром",
				"декаметре",
				"декаметры",
				"декаметров",
				"декаметрам",
				"декаметрами",
				"декаметрах",
			},
			results = {
				{ value = "10", unit = "м" },
				{ value = "32,81", unit = "фута" },
			},
		},
		metre = {
			name = "метр",
			system = "metric",
			category = "length",
			symbols = { "м" },
			forms = {
				"метр",
				"метра",
				"метру",
				"метром",
				"метре",
				"метры",
				"метров",
				"метрам",
				"метрами",
				"метрах",
			},
			results = { { value = "3,28084", unit = "фута" } },
		},
		decimetre = {
			name = "дециметр",
			system = "metric",
			category = "length",
			symbols = { "дм" },
			forms = {
				"дециметр",
				"дециметра",
				"дециметру",
				"дециметром",
				"дециметре",
				"дециметры",
				"дециметров",
				"дециметрам",
				"дециметрами",
				"дециметрах",
			},
			results = { { value = "3,937", unit = "дюйма" } },
		},
		centimetre = {
			name = "сантиметр",
			system = "metric",
			category = "length",
			symbols = { "см" },
			forms = {
				"сантиметр",
				"сантиметра",
				"сантиметру",
				"сантиметром",
				"сантиметре",
				"сантиметры",
				"сантиметров",
				"сантиметрам",
				"сантиметрами",
				"сантиметрах",
			},
			results = { { value = "0,3937", unit = "дюйма" } },
		},
		millimetre = {
			name = "миллиметр",
			system = "metric",
			category = "length",
			symbols = { "мм" },
			forms = {
				"миллиметр",
				"миллиметра",
				"миллиметру",
				"миллиметром",
				"миллиметре",
				"миллиметры",
				"миллиметров",
				"миллиметрам",
				"миллиметрами",
				"миллиметрах",
			},
			results = { { value = "0,03937", unit = "дюйма" } },
		},
		micrometre = {
			name = "микрометр",
			system = "metric",
			category = "length",
			symbols = { "мкм" },
			forms = {
				"микрометр",
				"микрометра",
				"микрометру",
				"микрометром",
				"микрометре",
				"микрометры",
				"микрометров",
				"микрометрам",
				"микрометрами",
				"микрометрах",
				"микрон",
				"микрона",
				"микроны",
				"микронов",
			},
			results = {
				{ value = "0,001", unit = "мм" },
				{ value = "1000", unit = "нм" },
			},
		},
		nanometre = {
			name = "нанометр",
			system = "metric",
			category = "length",
			symbols = { "нм" },
			forms = {
				"нанометр",
				"нанометра",
				"нанометру",
				"нанометром",
				"нанометре",
				"нанометры",
				"нанометров",
				"нанометрам",
				"нанометрами",
				"нанометрах",
			},
			results = {
				{ value = "0,001", unit = "мкм" },
				{ value = "0,000001", unit = "мм" },
			},
		},

		-- ── Mass / weight ─────────────────────────────────────────────────
		tonne = {
			name = "тонна",
			category = "mass",
			symbols = { "т" },
			forms = {
				"тонна",
				"тонны",
				"тонне",
				"тонну",
				"тонной",
				"тонною",
				"тонн",
				"тоннам",
				"тоннами",
				"тоннах",
			},
			results = {
				{ value = "1000", unit = "кг", label = "метрическая" },
				{ value = "1016", unit = "кг", label = "длинная (брит.)" },
				{ value = "907", unit = "кг", label = "короткая (амер.)" },
			},
		},
		quintal = {
			name = "центнер",
			system = "metric",
			category = "mass",
			symbols = { "ц" },
			forms = {
				"центнер",
				"центнера",
				"центнеру",
				"центнером",
				"центнере",
				"центнеры",
				"центнеров",
				"центнерам",
				"центнерами",
				"центнерах",
			},
			results = {
				{ value = "100", unit = "кг" },
				{ value = "220,5", unit = "фунта" },
			},
		},
		kilogram = {
			name = "килограмм",
			system = "metric",
			category = "mass",
			symbols = { "кг" },
			forms = {
				"килограмм",
				"килограмма",
				"килограмму",
				"килограммом",
				"килограмме",
				"килограммы",
				"килограммов",
				"килограммам",
				"килограммами",
				"килограммах",
			},
			results = { { value = "2,205", unit = "фунта" } },
		},
		gram = {
			name = "грамм",
			system = "metric",
			category = "mass",
			symbols = { "г" },
			forms = {
				"грамм",
				"грамма",
				"грамму",
				"граммом",
				"грамме",
				"граммы",
				"граммов",
				"граммам",
				"граммами",
				"граммах",
			},
			results = { { value = "0,0353", unit = "унции" } },
		},
		milligram = {
			name = "миллиграмм",
			system = "metric",
			category = "mass",
			symbols = { "мг" },
			forms = {
				"миллиграмм",
				"миллиграмма",
				"миллиграмму",
				"миллиграммом",
				"миллиграмме",
				"миллиграммы",
				"миллиграммов",
				"миллиграммам",
				"миллиграммами",
				"миллиграммах",
			},
			results = {
				{ value = "0,001", unit = "г" },
				{ value = "0,0154", unit = "грана" },
			},
		},
		microgram = {
			name = "микрограмм",
			system = "metric",
			category = "mass",
			symbols = { "мкг" },
			forms = {
				"микрограмм",
				"микрограмма",
				"микрограмму",
				"микрограммом",
				"микрограмме",
				"микрограммы",
				"микрограммов",
				"микрограммам",
				"микрограммами",
				"микрограммах",
			},
			results = {
				{ value = "0,001", unit = "мг" },
				{ value = "0,000001", unit = "г" },
			},
		},
		hundredweight = {
			name = "хандредвейт",
			system = "customary",
			category = "mass",
			forms = {
				"хандредвейт",
				"хандредвейта",
				"хандредвейту",
				"хандредвейтом",
				"хандредвейте",
				"хандредвейты",
				"хандредвейтов",
				"хандредвейтам",
				"хандредвейтами",
				"хандредвейтах",
			},
			results = {
				{ value = "50,8", unit = "кг", label = "длинный (брит.)" },
				{ value = "45,36", unit = "кг", label = "короткий (амер.)" },
			},
		},
		stone = {
			name = "стоун",
			system = "customary",
			category = "mass",
			forms = {
				"стоун",
				"стоуна",
				"стоуну",
				"стоуном",
				"стоуне",
				"стоуны",
				"стоунов",
				"стоунам",
				"стоунами",
				"стоунах",
			},
			results = { { value = "6,35", unit = "кг" } },
		},
		pound = {
			name = "фунт",
			system = "customary",
			category = "mass",
			forms = {
				"фунт",
				"фунта",
				"фунту",
				"фунтом",
				"фунте",
				"фунты",
				"фунтов",
				"фунтам",
				"фунтами",
				"фунтах",
			},
			results = { { value = "453,6", unit = "г" } },
		},
		ounce = {
			name = "унция",
			forms = {
				"унция",
				"унции",
				"унцию",
				"унцией",
				"унциею",
				"унций",
				"унциям",
				"унциями",
				"унциях",
			},
			results = {
				{ value = "28,35", unit = "г", label = "вес" },
				{ value = "29,57", unit = "мл", label = "жидк. (амер.)" },
				{ value = "28,41", unit = "мл", label = "жидк. (брит.)" },
			},
		},
		dram = {
			name = "драхма",
			system = "customary",
			category = "mass",
			forms = {
				"драхма",
				"драхмы",
				"драхме",
				"драхму",
				"драхмой",
				"драхмою",
				"драхм",
				"драхмам",
				"драхмами",
				"драхмах",
			},
			results = { { value = "3,888", unit = "г", label = "аптечная" } },
		},
		grain = {
			name = "гран",
			system = "customary",
			category = "mass",
			forms = {
				"гран",
				"грана",
				"грану",
				"граном",
				"гране",
				"граны",
				"гранов",
				"гранам",
				"гранами",
				"гранах",
			},
			results = { { value = "64,8", unit = "мг" } },
		},

		-- ── Volume ────────────────────────────────────────────────────────
		hectolitre = {
			name = "гектолитр",
			system = "metric",
			category = "volume",
			symbols = { "гл" },
			forms = {
				"гектолитр",
				"гектолитра",
				"гектолитру",
				"гектолитром",
				"гектолитре",
				"гектолитры",
				"гектолитров",
				"гектолитрам",
				"гектолитрами",
				"гектолитрах",
			},
			results = {
				{ value = "100", unit = "л" },
				{ value = "26,42", unit = "галлона", label = "амер." },
				{ value = "22", unit = "галлона", label = "брит." },
			},
		},
		litre = {
			name = "литр",
			system = "metric",
			category = "volume",
			symbols = { "л" },
			forms = {
				"литр",
				"литра",
				"литру",
				"литром",
				"литре",
				"литры",
				"литров",
				"литрам",
				"литрами",
				"литрах",
			},
			results = {
				{ value = "2,11", unit = "пинты", label = "амер." },
				{ value = "1,76", unit = "пинты", label = "брит." },
			},
		},
		decilitre = {
			name = "децилитр",
			system = "metric",
			category = "volume",
			symbols = { "дл" },
			forms = {
				"децилитр",
				"децилитра",
				"децилитру",
				"децилитром",
				"децилитре",
				"децилитры",
				"децилитров",
				"децилитрам",
				"децилитрами",
				"децилитрах",
			},
			results = {
				{ value = "100", unit = "мл" },
				{ value = "3,38", unit = "жидк. унции", label = "амер." },
				{ value = "3,52", unit = "жидк. унции", label = "брит." },
			},
		},
		millilitre = {
			name = "миллилитр",
			system = "metric",
			category = "volume",
			symbols = { "мл" },
			forms = {
				"миллилитр",
				"миллилитра",
				"миллилитру",
				"миллилитром",
				"миллилитре",
				"миллилитры",
				"миллилитров",
				"миллилитрам",
				"миллилитрами",
				"миллилитрах",
			},
			results = {
				{ value = "0,0338", unit = "жидк. унции", label = "амер." },
				{ value = "0,0352", unit = "жидк. унции", label = "брит." },
			},
		},
		gallon = {
			name = "галлон",
			system = "customary",
			category = "volume",
			forms = {
				"галлон",
				"галлона",
				"галлону",
				"галлоном",
				"галлоне",
				"галлоны",
				"галлонов",
				"галлонам",
				"галлонами",
				"галлонах",
			},
			results = {
				{ value = "3,785", unit = "л", label = "амер." },
				{ value = "4,546", unit = "л", label = "брит." },
			},
		},
		quart = {
			name = "кварта",
			system = "customary",
			category = "volume",
			forms = {
				"кварта",
				"кварты",
				"кварте",
				"кварту",
				"квартой",
				"квартою",
				"кварт",
				"квартам",
				"квартами",
				"квартах",
			},
			results = {
				{ value = "0,946", unit = "л", label = "амер." },
				{ value = "1,137", unit = "л", label = "брит." },
			},
		},
		pint = {
			name = "пинта",
			system = "customary",
			category = "volume",
			forms = {
				"пинта",
				"пинты",
				"пинте",
				"пинту",
				"пинтой",
				"пинтою",
				"пинт",
				"пинтам",
				"пинтами",
				"пинтах",
			},
			results = {
				{ value = "0,473", unit = "л", label = "амер." },
				{ value = "0,568", unit = "л", label = "брит." },
			},
		},
		barrel = {
			name = "баррель",
			system = "customary",
			category = "volume",
			forms = {
				"баррель",
				"барреля",
				"баррелю",
				"баррелем",
				"барреле",
				"баррели",
				"баррелей",
				"баррелям",
				"баррелями",
				"баррелях",
			},
			results = { { value = "158,99", unit = "л", label = "нефтяной" } },
		},

		-- ── Area ──────────────────────────────────────────────────────────
		hectare = {
			name = "гектар",
			system = "metric",
			category = "area",
			symbols = { "га" },
			forms = {
				"гектар",
				"гектара",
				"гектару",
				"гектаром",
				"гектаре",
				"гектары",
				"гектаров",
				"гектарам",
				"гектарами",
				"гектарах",
			},
			results = { { value = "2,471", unit = "акра" }, { value = "10000", unit = "м²" } },
		},
		are = {
			name = "сотка",
			system = "metric",
			category = "area",
			forms = {
				"сотка",
				"сотки",
				"сотке",
				"сотку",
				"соткой",
				"соткою",
				"соток",
				"соткам",
				"сотками",
				"сотках",
			},
			results = {
				{ value = "100", unit = "м²" },
				{ value = "0,0247", unit = "акра" },
			},
		},
		acre = {
			name = "акр",
			system = "customary",
			category = "area",
			forms = {
				"акр",
				"акра",
				"акру",
				"акром",
				"акре",
				"акры",
				"акров",
				"акрам",
				"акрами",
				"акрах",
			},
			results = {
				{ value = "0,405", unit = "га" },
				{ value = "4047", unit = "м²" },
			},
		},
	},
}
