--[[
dicts/ru.lua - Russian dictionary (length, mass, volume).

Format: see docs/spec.md §4. Values are precomputed strings with a comma decimal
mark (docs/units.md). Imperial units rarely carry symbols in Russian prose, so
only the metric side declares digit-gated symbols (м, см, мм, км, г, кг, т, ц, л).

Only single-word forms are listed: the matcher tests one token at a time, so
multi-word units (жидкая унция, кубический метр, миля в час, квадратный метр) are
deferred until phrase matching lands — this is why area/speed are not here yet.
Where US and British Imperial diverge (galon, pint, quart, bushel), both variants
are shown as separate labelled results (США / Великобритания).
]]

return {
	lang = "ru",
	name = "Русский",

	strings = {
		system_label = "Система",
		category_label = "Категория",
		systems = { customary = "Имперская", metric = "Метрическая" },
		categories = { length = "Длина", mass = "Масса", volume = "Объём" },
	},

	units = {

		-- ── Length ────────────────────────────────────────────────────────

		league = {
			name = "лига",
			system = "customary",
			category = "length",
			forms = {
				"лига",
				"лиги",
				"лиге",
				"лигу",
				"лигой",
				"лигою",
				"лиг",
				"лигам",
				"лигами",
				"лигах",
			},
			results = { { value = "4,828", unit = "км" } },
		},
		mile = {
			name = "миля",
			system = "customary",
			category = "length",
			forms = {
				"миля",
				"мили",
				"миле",
				"милю",
				"милей",
				"милею",
				"миль",
				"милям",
				"милями",
				"милях",
			},
			results = {
				{ value = "1,609", unit = "км", label = "сухопутная" },
				{ value = "1,852", unit = "км", label = "морская" },
			},
		},
		furlong = {
			name = "фурлонг",
			system = "customary",
			category = "length",
			forms = {
				"фурлонг",
				"фурлонга",
				"фурлонгу",
				"фурлонгом",
				"фурлонге",
				"фурлонги",
				"фурлонгов",
				"фурлонгам",
				"фурлонгами",
				"фурлонгах",
			},
			results = { { value = "201,17", unit = "м" } },
		},
		chain = {
			name = "чейн",
			system = "customary",
			category = "length",
			forms = {
				"чейн",
				"чейна",
				"чейну",
				"чейном",
				"чейне",
				"чейны",
				"чейнов",
				"чейнам",
				"чейнами",
				"чейнах",
			},
			results = { { value = "20,117", unit = "м" } },
		},
		yard = {
			name = "ярд",
			system = "customary",
			category = "length",
			forms = {
				"ярд",
				"ярда",
				"ярду",
				"ярдом",
				"ярде",
				"ярды",
				"ярдов",
				"ярдам",
				"ярдами",
				"ярдах",
			},
			results = { { value = "0,9144", unit = "м" } },
		},
		foot = {
			name = "фут",
			system = "customary",
			category = "length",
			forms = {
				"фут",
				"фута",
				"футу",
				"футом",
				"футе",
				"футы",
				"футов",
				"футам",
				"футами",
				"футах",
			},
			results = { { value = "0,3048", unit = "м" } },
		},
		inch = {
			name = "дюйм",
			system = "customary",
			category = "length",
			forms = {
				"дюйм",
				"дюйма",
				"дюйму",
				"дюймом",
				"дюйме",
				"дюймы",
				"дюймов",
				"дюймам",
				"дюймами",
				"дюймах",
			},
			results = { { value = "2,54", unit = "см" } },
		},
		kilometre = {
			name = "километр",
			system = "metric",
			category = "length",
			symbols = { "км" },
			forms = {
				"километр",
				"километра",
				"километру",
				"километром",
				"километре",
				"километры",
				"километров",
				"километрам",
				"километрами",
				"километрах",
			},
			results = { { value = "0,6214", unit = "мили" } },
		},
		hectometre = {
			name = "гектометр",
			system = "metric",
			category = "length",
			symbols = { "гм" },
			forms = {
				"гектометр",
				"гектометра",
				"гектометру",
				"гектометром",
				"гектометре",
				"гектометры",
				"гектометров",
				"гектометрам",
				"гектометрами",
				"гектометрах",
			},
			results = {
				{ value = "100", unit = "м" },
				{ value = "328,08", unit = "фута" },
			},
		},
		decametre = {
			name = "декаметр",
			system = "metric",
			category = "length",
			symbols = { "дам" },
			forms = {
				"декаметр",
				"декаметра",
				"декаметру",
				"декаметром",
				"декаметре",
				"декаметры",
				"декаметров",
				"декаметрам",
				"декаметрами",
				"декаметрах",
			},
			results = {
				{ value = "10", unit = "м" },
				{ value = "32,81", unit = "фута" },
			},
		},
		metre = {
			name = "метр",
			system = "metric",
			category = "length",
			symbols = { "м" },
			forms = {
				"метр",
				"метра",
				"метру",
				"метром",
				"метре",
				"метры",
				"метров",
				"метрам",
				"метрами",
				"метрах",
			},
			results = { { value = "3,28084", unit = "фута" } },
		},
		decimetre = {
			name = "дециметр",
			system = "metric",
			category = "length",
			symbols = { "дм" },
			forms = {
				"дециметр",
				"дециметра",
				"дециметру",
				"дециметром",
				"дециметре",
				"дециметры",
				"дециметров",
				"дециметрам",
				"дециметрами",
				"дециметрах",
			},
			results = { { value = "3,937", unit = "дюйма" } },
		},
		centimetre = {
			name = "сантиметр",
			system = "metric",
			category = "length",
			symbols = { "см" },
			forms = {
				"сантиметр",
				"сантиметра",
				"сантиметру",
				"сантиметром",
				"сантиметре",
				"сантиметры",
				"сантиметров",
				"сантиметрам",
				"сантиметрами",
				"сантиметрах",
			},
			results = { { value = "0,3937", unit = "дюйма" } },
		},
		millimetre = {
			name = "миллиметр",
			system = "metric",
			category = "length",
			symbols = { "мм" },
			forms = {
				"миллиметр",
				"миллиметра",
				"миллиметру",
				"миллиметром",
				"миллиметре",
				"миллиметры",
				"миллиметров",
				"миллиметрам",
				"миллиметрами",
				"миллиметрах",
			},
			results = { { value = "0,03937", unit = "дюйма" } },
		},
		micrometre = {
			name = "микрометр",
			system = "metric",
			category = "length",
			symbols = { "мкм" },
			forms = {
				"микрометр",
				"микрометра",
				"микрометру",
				"микрометром",
				"микрометре",
				"микрометры",
				"микрометров",
				"микрометрам",
				"микрометрами",
				"микрометрах",
				"микрон",
				"микрона",
				"микроны",
				"микронов",
			},
			results = {
				{ value = "0,001", unit = "мм" },
				{ value = "1000", unit = "нм" },
			},
		},
		nanometre = {
			name = "нанометр",
			system = "metric",
			category = "length",
			symbols = { "нм" },
			forms = {
				"нанометр",
				"нанометра",
				"нанометру",
				"нанометром",
				"нанометре",
				"нанометры",
				"нанометров",
				"нанометрам",
				"нанометрами",
				"нанометрах",
			},
			results = {
				{ value = "0,001", unit = "мкм" },
				{ value = "0,000001", unit = "мм" },
			},
		},
	},
}
